linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gocritic

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style

issues:
  exclude-dirs:
    - testdata
  max-issues-per-linter: 50
  max-same-issues: 10
