package cmd

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/justn-hyeok/ganbatte/internal/config"
	"github.com/justn-hyeok/ganbatte/internal/shell"
	"github.com/spf13/cobra"
)

// shellInitCmd represents the shell-init command
var shellInitCmd = &cobra.Command{
	Use:   "shell-init",
	Short: "Output shell functions for registered aliases and workflows",
	Long: `Output shell functions that can be eval'd to register aliases and workflows
as native shell commands.

Add this to your shell config:
  # bash/zsh
  eval "$(gnb shell-init)"

  # fish
  gnb shell-init | source

Powerlevel10k users: place the eval line BEFORE the instant prompt preamble
in ~/.zshrc, or run 'gnb doctor --fix' to reorder automatically.

Example:
  gnb shell-init
  gnb shell-init --shell fish`,
	RunE: func(cmd *cobra.Command, args []string) error {
		shellFlag, _ := cmd.Flags().GetString("shell")

		sh := shellFlag
		if sh == "" {
			sh = shell.Detect()
		}

		cfg, err := config.Load()
		if err != nil {
			return fmt.Errorf("loading config: %w", err)
		}

		output := generateShellInit(cfg, sh)
		fmt.Fprint(os.Stdout, output)
		return nil
	},
}

func generateShellInit(cfg *config.Config, sh string) string {
	var b strings.Builder

	b.WriteString("# Generated by ganbatte (gnb shell-init)\n")
	b.WriteString("# Do not edit manually.\n\n")

	// Passive tracking hook — writes to track.log without spawning gnb binary
	switch sh {
	case "fish":
		b.WriteString(`# ganbatte passive tracking
function _gnb_track --on-event fish_postexec
  set -l _log (test -n "$XDG_DATA_HOME"; and echo "$XDG_DATA_HOME/ganbatte/track.log"; or echo "$HOME/.local/share/ganbatte/track.log")
  mkdir -p (dirname $_log) 2>/dev/null
  printf '%s\t%s\t%s\n' (date +%s) $status "$argv" >> $_log 2>/dev/null
end

`)
	case "zsh":
		b.WriteString(`# ganbatte passive tracking
_gnb_preexec() { _gnb_cmd="$1"; }
_gnb_precmd() {
  local _exit=$?
  if [[ -n "${_gnb_cmd:-}" ]]; then
    local _log="${XDG_DATA_HOME:-$HOME/.local/share}/ganbatte/track.log"
    mkdir -p "${_log:h}" 2>/dev/null
    printf '%s\t%s\t%s\n' "$(date +%s)" "$_exit" "$_gnb_cmd" >> "$_log" 2>/dev/null
    _gnb_cmd=
  fi
}
preexec_functions+=(_gnb_preexec)
precmd_functions+=(_gnb_precmd)

`)
	default: // bash
		b.WriteString(`# ganbatte passive tracking
_gnb_debug() {
  [[ "$BASH_COMMAND" != _gnb_* ]] && _gnb_cmd="$BASH_COMMAND"
}
_gnb_prompt() {
  local _exit=$?
  if [[ -n "${_gnb_cmd:-}" ]]; then
    local _log="${XDG_DATA_HOME:-$HOME/.local/share}/ganbatte/track.log"
    mkdir -p "$(dirname "$_log")" 2>/dev/null
    printf '%s\t%s\t%s\n' "$(date +%s)" "$_exit" "$_gnb_cmd" >> "$_log" 2>/dev/null
    _gnb_cmd=
  fi
}
trap '_gnb_debug' DEBUG
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND; }_gnb_prompt"

`)
	}

	// Collect and sort names for deterministic output
	names := make([]string, 0, len(cfg.Aliases)+len(cfg.Workflows))
	for name := range cfg.Aliases {
		names = append(names, name)
	}
	for name := range cfg.Workflows {
		names = append(names, name)
	}
	sort.Strings(names)

	switch sh {
	case "fish":
		for _, name := range names {
			if !isValidFunctionName(name) {
				b.WriteString(fmt.Sprintf("# skipped '%s': invalid function name\n", name))
				continue
			}
			b.WriteString(fmt.Sprintf("function %s; gnb run %s $argv; end\n", name, name))
		}
	default: // bash, zsh
		for _, name := range names {
			if !isValidFunctionName(name) {
				b.WriteString(fmt.Sprintf("# skipped '%s': invalid function name\n", name))
				continue
			}
			b.WriteString(fmt.Sprintf("%s() { gnb run %s \"$@\"; }\n", name, name))
		}
	}

	return b.String()
}

// isValidFunctionName checks if the name can be used as a shell function name.
// Allows alphanumeric, hyphens, and underscores. Must start with a letter or underscore.
func isValidFunctionName(name string) bool {
	if name == "" {
		return false
	}
	first := name[0]
	if !((first >= 'a' && first <= 'z') || (first >= 'A' && first <= 'Z') || first == '_') {
		return false
	}
	for _, c := range name[1:] {
		if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' || c == '-') {
			return false
		}
	}
	return true
}

func init() {
	shellInitCmd.Flags().String("shell", "", "Shell type (bash, zsh, fish). Auto-detected if omitted")
	RootCmd.AddCommand(shellInitCmd)
}
