package cmd

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/justn-hyeok/ganbatte/internal/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateShellInit_BashZsh(t *testing.T) {
	cfg := &config.Config{
		Aliases: map[string]config.Alias{
			"gs": {Cmd: "git status -sb"},
			"gl": {Cmd: "git log --oneline -10"},
		},
		Workflows: map[string]config.Workflow{
			"deploy": {Description: "Deploy to prod"},
		},
	}

	output := generateShellInit(cfg, "zsh")

	assert.Contains(t, output, "gs() { gnb run gs \"$@\"; }")
	assert.Contains(t, output, "gl() { gnb run gl \"$@\"; }")
	assert.Contains(t, output, "deploy() { gnb run deploy \"$@\"; }")
	assert.Contains(t, output, "preexec_functions+=(_gnb_preexec)")

	// bash has different hooks but same alias functions
	bashOutput := generateShellInit(cfg, "bash")
	assert.Contains(t, bashOutput, "gs() { gnb run gs \"$@\"; }")
	assert.Contains(t, bashOutput, "trap '_gnb_debug' DEBUG")
}

func TestGenerateShellInit_Fish(t *testing.T) {
	cfg := &config.Config{
		Aliases: map[string]config.Alias{
			"gs": {Cmd: "git status -sb"},
		},
		Workflows: map[string]config.Workflow{
			"deploy": {Description: "Deploy to prod"},
		},
	}

	output := generateShellInit(cfg, "fish")

	assert.Contains(t, output, "function gs; gnb run gs $argv; end")
	assert.Contains(t, output, "function deploy; gnb run deploy $argv; end")
	assert.NotContains(t, output, "\"$@\"")
}

func TestGenerateShellInit_Empty(t *testing.T) {
	cfg := &config.Config{
		Aliases:   map[string]config.Alias{},
		Workflows: map[string]config.Workflow{},
	}

	output := generateShellInit(cfg, "zsh")

	assert.Contains(t, output, "# Generated by ganbatte")
	// No alias functions should appear (only tracking hooks)
	assert.NotContains(t, output, "gnb run")
}

func TestGenerateShellInit_SortedOutput(t *testing.T) {
	cfg := &config.Config{
		Aliases: map[string]config.Alias{
			"zz": {Cmd: "echo z"},
			"aa": {Cmd: "echo a"},
			"mm": {Cmd: "echo m"},
		},
		Workflows: map[string]config.Workflow{},
	}

	output := generateShellInit(cfg, "bash")

	aaIdx := indexOf(output, "aa()")
	mmIdx := indexOf(output, "mm()")
	zzIdx := indexOf(output, "zz()")

	require.Greater(t, aaIdx, -1)
	require.Greater(t, mmIdx, -1)
	require.Greater(t, zzIdx, -1)
	assert.Less(t, aaIdx, mmIdx)
	assert.Less(t, mmIdx, zzIdx)
}

func TestGenerateShellInit_InvalidNames(t *testing.T) {
	cfg := &config.Config{
		Aliases: map[string]config.Alias{
			"valid_name": {Cmd: "echo ok"},
			"123bad":     {Cmd: "echo bad"},
			"has space":  {Cmd: "echo bad"},
			"ok-hyphen":  {Cmd: "echo ok"},
		},
		Workflows: map[string]config.Workflow{},
	}

	output := generateShellInit(cfg, "zsh")

	assert.Contains(t, output, "valid_name()")
	assert.Contains(t, output, "ok-hyphen()")
	assert.Contains(t, output, "# skipped '123bad'")
	assert.Contains(t, output, "# skipped 'has space'")
}

func TestIsValidFunctionName(t *testing.T) {
	tests := []struct {
		name  string
		valid bool
	}{
		{"gs", true},
		{"git_status", true},
		{"my-alias", true},
		{"_private", true},
		{"Deploy", true},
		{"a1", true},
		{"", false},
		{"1bad", false},
		{"-bad", false},
		{"has space", false},
		{"semi;colon", false},
		{"do$llar", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.valid, isValidFunctionName(tt.name))
		})
	}
}

func TestShellInitCommand(t *testing.T) {
	home := setupTestHome(t)

	// Create config with aliases
	configDir := filepath.Join(home, ".config", "ganbatte")
	require.NoError(t, os.MkdirAll(configDir, 0o755))
	require.NoError(t, os.WriteFile(
		filepath.Join(configDir, "config.toml"),
		[]byte(`version = "1.0.0"
[alias.gs]
cmd = "git status -sb"
[alias.gl]
cmd = "git log --oneline"
`), 0o644))

	out, err := executeCmd("shell-init", "--shell", "zsh")
	require.NoError(t, err)

	assert.Contains(t, out, "gs() { gnb run gs \"$@\"; }")
	assert.Contains(t, out, "gl() { gnb run gl \"$@\"; }")
}

func TestShellInitCommand_Fish(t *testing.T) {
	home := setupTestHome(t)

	configDir := filepath.Join(home, ".config", "ganbatte")
	require.NoError(t, os.MkdirAll(configDir, 0o755))
	require.NoError(t, os.WriteFile(
		filepath.Join(configDir, "config.toml"),
		[]byte(`version = "1.0.0"
[alias.gs]
cmd = "git status -sb"
`), 0o644))

	out, err := executeCmd("shell-init", "--shell", "fish")
	require.NoError(t, err)

	assert.Contains(t, out, "function gs; gnb run gs $argv; end")
}

// indexOf returns the index of substr in s, or -1.
func indexOf(s, substr string) int {
	for i := 0; i+len(substr) <= len(s); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
